import { Account, Category, Project, RecurringExpense, Transaction } from '../types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-dining',
    name: 'Dining & Food',
    icon: 'UtensilsCrossed',
    color: '#f97316', // Orange
    subcategories: ['Restaurants', 'Coffee Shops', 'Fast Food', 'Bars & Pubs', 'Delivery & Takeout'],
    monthlyBudget: 650,
    rulesKeywords: ['starbucks', 'mcdonald', 'chipotle', 'uber eats', 'doordash', 'restaurant', 'cafe', 'coffee', 'pizza', 'sushi', 'diner', 'grill', 'bakery'],
  },
  {
    id: 'cat-groceries',
    name: 'Groceries',
    icon: 'ShoppingCart',
    color: '#10b981', // Emerald
    subcategories: ['Supermarkets', 'Organic Stores', 'Farmers Market', 'Beverages', 'Pantry'],
    monthlyBudget: 500,
    rulesKeywords: ['whole foods', 'trader joe', 'kroger', 'safeway', 'walmart', 'target grocery', 'costco food', 'supermarket', 'market', 'produce'],
  },
  {
    id: 'cat-housing',
    name: 'Housing & Rent',
    icon: 'Home',
    color: '#3b82f6', // Blue
    subcategories: ['Rent / Mortgage', 'Property Tax', 'Home Maintenance', 'Furniture', 'HOA Fees'],
    monthlyBudget: 1800,
    rulesKeywords: ['rent', 'mortgage', 'landlord', 'apartment', 'property', 'maintenance', 'home depot', 'ikea', 'furniture'],
  },
  {
    id: 'cat-utilities',
    name: 'Utilities & Bills',
    icon: 'Zap',
    color: '#eab308', // Yellow
    subcategories: ['Electricity', 'Water', 'Internet', 'Mobile Phone', 'Gas & Heating', 'Trash'],
    monthlyBudget: 320,
    rulesKeywords: ['electric', 'pge', 'coned', 'verizon', 'at&t', 't-mobile', 'comcast', 'xfinity', 'water dept', 'utilities', 'gas bill', 'wifi'],
  },
  {
    id: 'cat-transport',
    name: 'Transportation',
    icon: 'Car',
    color: '#8b5cf6', // Purple
    subcategories: ['Gasoline / Fuel', 'Public Transit', 'Rideshare / Taxi', 'Parking & Tolls', 'Auto Maintenance'],
    monthlyBudget: 280,
    rulesKeywords: ['gas', 'fuel', 'shell', 'chevron', 'exxon', 'uber trip', 'lyft', 'subway', 'metro', 'transit', 'parking', 'toll', 'oil change', 'car wash'],
  },
  {
    id: 'cat-shopping',
    name: 'Shopping & Retail',
    icon: 'ShoppingBag',
    color: '#ec4899', // Pink
    subcategories: ['Clothing & Apparel', 'Electronics & Gadgets', 'Home Goods', 'Books & Hobbies', 'Gifts'],
    monthlyBudget: 400,
    rulesKeywords: ['amazon', 'apple store', 'best buy', 'zara', 'nike', 'nordstrom', 'target', 'ebay', 'clothing', 'shoes', 'electronics'],
  },
  {
    id: 'cat-entertainment',
    name: 'Entertainment',
    icon: 'Film',
    color: '#06b6d4', // Cyan
    subcategories: ['Movies & Cinema', 'Concerts & Events', 'Gaming', 'Outdoor Activities', 'Streaming'],
    monthlyBudget: 200,
    rulesKeywords: ['amc', 'cinema', 'steam', 'playstation', 'nintendo', 'ticketmaster', 'concert', 'museum', 'bowling', 'theme park'],
  },
  {
    id: 'cat-subscriptions',
    name: 'Subscriptions & SaaS',
    icon: 'Repeat',
    color: '#6366f1', // Indigo
    subcategories: ['Streaming Video', 'Music', 'Cloud Storage', 'Software Tools', 'Fitness Apps'],
    monthlyBudget: 95,
    rulesKeywords: ['netflix', 'spotify', 'apple.com/bill', 'youtube premium', 'github', 'chatgpt', 'openai', 'notion', 'icloud', 'hulu', 'disney+', 'prime video'],
  },
  {
    id: 'cat-health',
    name: 'Healthcare & Fitness',
    icon: 'HeartPulse',
    color: '#ef4444', // Red
    subcategories: ['Pharmacy & Meds', 'Doctor Visits', 'Dental Care', 'Gym Membership', 'Supplements'],
    monthlyBudget: 250,
    rulesKeywords: ['cvs', 'walgreens', 'pharmacy', 'hospital', 'clinic', 'dentist', 'equinox', 'planet fitness', 'gym', 'gnc', 'vitamins'],
  },
  {
    id: 'cat-travel',
    name: 'Travel & Vacation',
    icon: 'Plane',
    color: '#14b8a6', // Teal
    subcategories: ['Flights', 'Hotels & Airbnb', 'Car Rental', 'Travel Insurance', 'Excursions'],
    monthlyBudget: 350,
    rulesKeywords: ['delta', 'united airlines', 'american airlines', 'airbnb', 'marriott', 'hilton', 'booking.com', 'expedia', 'hotel', 'flight', 'hertz'],
  },
  {
    id: 'cat-business',
    name: 'Business & Office',
    icon: 'Briefcase',
    color: '#64748b', // Slate
    subcategories: ['Office Supplies', 'Client Dinners', 'Professional Services', 'Travel & Meals', 'Advertising'],
    monthlyBudget: 300,
    type: 'expense',
    rulesKeywords: ['staples', 'fedex', 'ups', 'google ads', 'facebook ads', 'linkedin', 'consulting', 'coworking', 'wework', 'domain'],
  },
  // Income Categories
  {
    id: 'cat-salary',
    name: 'Salary & Wages',
    icon: 'Briefcase',
    color: '#10b981', // Emerald
    subcategories: ['Direct Deposit', 'Base Salary', 'Overtime', 'Annual Bonus', 'Commission'],
    type: 'income',
    rulesKeywords: ['salary', 'payroll', 'direct deposit', 'tech corp', 'wages', 'employer', 'paycheck'],
  },
  {
    id: 'cat-freelance',
    name: 'Freelance & Consulting',
    icon: 'Laptop',
    color: '#06b6d4', // Cyan
    subcategories: ['Client Projects', 'Consulting Fees', 'Design Work', 'Writing & Content', 'Retainers'],
    type: 'income',
    rulesKeywords: ['freelance', 'consulting', 'client payment', 'upwork', 'fiverr', 'contract', 'invoice payment', 'stripe payout'],
  },
  {
    id: 'cat-investments',
    name: 'Investments & Dividends',
    icon: 'TrendingUp',
    color: '#8b5cf6', // Purple
    subcategories: ['Stock Dividends', 'Interest Income', 'Capital Gains', 'Crypto Gains', 'Staking Rewards'],
    type: 'income',
    rulesKeywords: ['dividend', 'interest earned', 'marcus interest', 'vanguard', 'fidelity', 'robinhood payout', 'capital gain'],
  },
  {
    id: 'cat-refunds',
    name: 'Refunds & Reimbursements',
    icon: 'RotateCcw',
    color: '#ec4899', // Pink
    subcategories: ['Store Returns', 'Expense Reimbursement', 'Tax Refund', 'Cashback Rewards'],
    type: 'income',
    rulesKeywords: ['refund', 'reimbursement', 'cashback', 'credit return', 'tax refund', 'irs'],
  },
  {
    id: 'cat-other-income',
    name: 'Other Income',
    icon: 'Coins',
    color: '#eab308', // Amber
    subcategories: ['Gifts & Grants', 'Rental Inflow', 'Side Hustle', 'Misc Deposit'],
    type: 'income',
    rulesKeywords: ['deposit', 'gift', 'transfer received', 'received from', 'venmo received', 'zelle received'],
  },
];

export const INITIAL_ACCOUNTS: Account[] = [
  {
    id: 'acc-chase-checking',
    name: 'Chase Premier Checking',
    type: 'checking',
    currency: 'USD',
    balance: 8420.50,
    initialBalance: 10000,
    accountNumberMasked: '•••• 4821',
    color: '#2563eb',
    institution: 'JPMorgan Chase',
  },
  {
    id: 'acc-amex-gold',
    name: 'Amex Gold Card',
    type: 'credit',
    currency: 'USD',
    balance: -1640.25,
    initialBalance: 0,
    accountNumberMasked: '•••• 1008',
    color: '#d97706',
    institution: 'American Express',
  },
  {
    id: 'acc-apple-card',
    name: 'Apple Card (Mastercard)',
    type: 'credit',
    currency: 'USD',
    balance: -680.10,
    initialBalance: 0,
    accountNumberMasked: '•••• 9433',
    color: '#64748b',
    institution: 'Goldman Sachs',
  },
  {
    id: 'acc-high-yield-savings',
    name: 'Marcus High-Yield Savings',
    type: 'savings',
    currency: 'USD',
    balance: 24500.00,
    initialBalance: 24000,
    accountNumberMasked: '•••• 7712',
    color: '#059669',
    institution: 'Goldman Sachs',
  },
  {
    id: 'acc-cash-wallet',
    name: 'Cash Physical Wallet',
    type: 'cash',
    currency: 'USD',
    balance: 340.00,
    initialBalance: 400,
    color: '#10b981',
    institution: 'Physical Cash',
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-japan-trip',
    name: 'Tokyo & Kyoto Vacation 2026',
    description: 'Travel expenses, bullet train tickets, hotels, ramen tours, and souvenirs.',
    budget: 3800,
    currency: 'USD',
    startDate: '2026-08-10',
    endDate: '2026-09-30',
    color: '#ec4899',
    icon: 'Plane',
    status: 'active',
  },
  {
    id: 'proj-home-office',
    name: 'Home Office Ergonomic Upgrade',
    description: 'Standing desk, ergonomic chair, 4K monitor, and acoustic wall panels.',
    budget: 1500,
    currency: 'USD',
    startDate: '2026-07-01',
    endDate: '2026-09-15',
    color: '#3b82f6',
    icon: 'Laptop',
    status: 'active',
  },
  {
    id: 'proj-client-rebrand',
    name: 'Client Alpha Rebrand Project',
    description: 'Reimbursable business project expenses for client brand collateral.',
    budget: 2200,
    currency: 'USD',
    startDate: '2026-08-01',
    color: '#8b5cf6',
    icon: 'Briefcase',
    status: 'active',
  },
];

export const INITIAL_RECURRING: RecurringExpense[] = [
  {
    id: 'rec-rent',
    name: 'Apartment Monthly Rent',
    merchant: 'Metropolitan Real Estate',
    amount: 1750.00,
    currency: 'USD',
    category: 'Housing & Rent',
    accountId: 'acc-chase-checking',
    frequency: 'monthly',
    billingDayOfMonth: 1,
    nextBillingDate: '2026-09-01',
    status: 'active',
    autoLog: true,
  },
  {
    id: 'rec-netflix',
    name: 'Netflix Premium 4K',
    merchant: 'Netflix.com',
    amount: 22.99,
    currency: 'USD',
    category: 'Subscriptions & SaaS',
    accountId: 'acc-apple-card',
    frequency: 'monthly',
    billingDayOfMonth: 14,
    nextBillingDate: '2026-09-14',
    status: 'active',
    autoLog: true,
  },
  {
    id: 'rec-spotify',
    name: 'Spotify Family Plan',
    merchant: 'Spotify USA',
    amount: 16.99,
    currency: 'USD',
    category: 'Subscriptions & SaaS',
    accountId: 'acc-apple-card',
    frequency: 'monthly',
    billingDayOfMonth: 22,
    nextBillingDate: '2026-09-22',
    status: 'active',
    autoLog: true,
  },
  {
    id: 'rec-gym',
    name: 'Equinox Fitness Club',
    merchant: 'Equinox Holdings',
    amount: 195.00,
    currency: 'USD',
    category: 'Healthcare & Fitness',
    accountId: 'acc-amex-gold',
    frequency: 'monthly',
    billingDayOfMonth: 5,
    nextBillingDate: '2026-09-05',
    status: 'active',
    autoLog: true,
  },
  {
    id: 'rec-chatgpt',
    name: 'ChatGPT Plus & Cloud Pro',
    merchant: 'OpenAI Services',
    amount: 20.00,
    currency: 'USD',
    category: 'Subscriptions & SaaS',
    accountId: 'acc-apple-card',
    frequency: 'monthly',
    billingDayOfMonth: 8,
    nextBillingDate: '2026-09-08',
    status: 'active',
    autoLog: true,
  },
  {
    id: 'rec-internet',
    name: 'Fiber Gigabit Internet',
    merchant: 'Sonic Fiber Corp',
    amount: 70.00,
    currency: 'USD',
    category: 'Utilities & Bills',
    accountId: 'acc-chase-checking',
    frequency: 'monthly',
    billingDayOfMonth: 18,
    nextBillingDate: '2026-09-18',
    status: 'active',
    autoLog: true,
  },
];

// Helper to generate dates relative to current date (2026-09-01)
export const INITIAL_TRANSACTIONS: Transaction[] = [
  // Current Month Incomes (September 2026)
  {
    id: 'tx-inc-001',
    type: 'income',
    date: '2026-09-01',
    merchant: 'Acme Tech Corp (Payroll)',
    amount: 5400.00,
    currency: 'USD',
    amountInUSD: 5400.00,
    category: 'Salary & Wages',
    subcategory: 'Direct Deposit',
    accountId: 'acc-chase-checking',
    tags: ['Salary', 'PrimaryIncome'],
    notes: 'Bi-weekly Direct Deposit Salary',
    aiCategorized: true,
    clearSpendsConfidence: 0.99,
    createdAt: '2026-09-01T06:00:00Z',
    updatedAt: '2026-09-01T06:00:00Z',
  },
  {
    id: 'tx-inc-002',
    type: 'income',
    date: '2026-08-28',
    merchant: 'Stripe Payout (Freelance Design)',
    amount: 1450.00,
    currency: 'USD',
    amountInUSD: 1450.00,
    category: 'Freelance & Consulting',
    subcategory: 'Design Work',
    accountId: 'acc-chase-checking',
    tags: ['Freelance', 'SideIncome'],
    notes: 'Mobile app UI design milestone completion payout',
    aiCategorized: true,
    clearSpendsConfidence: 0.98,
    createdAt: '2026-08-28T16:00:00Z',
    updatedAt: '2026-08-28T16:00:00Z',
  },
  {
    id: 'tx-inc-003',
    type: 'income',
    date: '2026-08-15',
    merchant: 'Marcus HYSA Monthly Interest',
    amount: 88.40,
    currency: 'USD',
    amountInUSD: 88.40,
    category: 'Investments & Dividends',
    subcategory: 'Interest Income',
    accountId: 'acc-high-yield-savings',
    tags: ['PassiveIncome', 'Interest'],
    notes: 'High-yield savings monthly APY accrued',
    aiCategorized: true,
    clearSpendsConfidence: 0.99,
    createdAt: '2026-08-15T01:00:00Z',
    updatedAt: '2026-08-15T01:00:00Z',
  },
  // Current Month Expenses (September 2026)
  {
    id: 'tx-001',
    type: 'expense',
    date: '2026-09-01',
    merchant: 'Metropolitan Real Estate',
    amount: 1750.00,
    currency: 'USD',
    amountInUSD: 1750.00,
    category: 'Housing & Rent',
    subcategory: 'Rent / Mortgage',
    accountId: 'acc-chase-checking',
    tags: ['Fixed', 'Monthly'],
    notes: 'September Rent for 2B2B',
    isRecurring: true,
    recurringId: 'rec-rent',
    aiCategorized: true,
    clearSpendsConfidence: 0.99,
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'tx-002',
    date: '2026-09-01',
    merchant: 'Blue Bottle Coffee',
    amount: 8.75,
    currency: 'USD',
    amountInUSD: 8.75,
    category: 'Dining & Food',
    subcategory: 'Coffee Shops',
    accountId: 'acc-amex-gold',
    tags: ['DailyCoffee', 'Morning'],
    lineItems: [
      { name: 'Bella Donovan Pour-over', quantity: 1, price: 5.75 },
      { name: 'Almond Croissant', quantity: 1, price: 3.00 },
    ],
    aiCategorized: true,
    clearSpendsConfidence: 0.98,
    createdAt: '2026-09-01T09:15:00Z',
    updatedAt: '2026-09-01T09:15:00Z',
  },
  {
    id: 'tx-003',
    date: '2026-08-30',
    merchant: 'Whole Foods Market',
    amount: 114.60,
    currency: 'USD',
    amountInUSD: 114.60,
    category: 'Groceries',
    subcategory: 'Supermarkets',
    accountId: 'acc-amex-gold',
    tags: ['Organic', 'WeeklyGrocery'],
    lineItems: [
      { name: 'Organic Honeycrisp Apples', quantity: 1, price: 8.40 },
      { name: 'Wild Caught Salmon Fillet', quantity: 1, price: 24.50 },
      { name: 'Oat Milk 64oz', quantity: 2, price: 9.98 },
      { name: 'Fresh Salad Kit', quantity: 3, price: 17.97 },
      { name: 'Greek Yogurt & Granola', quantity: 2, price: 13.50 },
      { name: 'Miscellaneous Pantry Items', quantity: 1, price: 40.25 },
    ],
    tax: 9.80,
    aiCategorized: true,
    clearSpendsConfidence: 0.99,
    createdAt: '2026-08-30T17:40:00Z',
    updatedAt: '2026-08-30T17:40:00Z',
  },
  {
    id: 'tx-004',
    date: '2026-08-29',
    merchant: 'Chipotle Mexican Grill',
    amount: 24.15,
    currency: 'USD',
    amountInUSD: 24.15,
    category: 'Dining & Food',
    subcategory: 'Fast Food',
    accountId: 'acc-amex-gold',
    tags: ['Lunch'],
    aiCategorized: true,
    clearSpendsConfidence: 0.99,
    createdAt: '2026-08-29T12:30:00Z',
    updatedAt: '2026-08-29T12:30:00Z',
  },
  {
    id: 'tx-005',
    date: '2026-08-28',
    merchant: 'Japan Airlines (JAL)',
    amount: 1240.00,
    currency: 'USD',
    amountInUSD: 1240.00,
    category: 'Travel & Vacation',
    subcategory: 'Flights',
    accountId: 'acc-amex-gold',
    tags: ['Vacation', 'Flight', 'Asia'],
    projectId: 'proj-japan-trip',
    notes: 'Roundtrip Tokyo Haneda flights for autumn vacation',
    aiCategorized: true,
    clearSpendsConfidence: 0.99,
    createdAt: '2026-08-28T14:20:00Z',
    updatedAt: '2026-08-28T14:20:00Z',
  },
  {
    id: 'tx-006',
    date: '2026-08-27',
    merchant: 'Chevron Gas Station',
    amount: 52.40,
    currency: 'USD',
    amountInUSD: 52.40,
    category: 'Transportation',
    subcategory: 'Gasoline / Fuel',
    accountId: 'acc-chase-checking',
    tags: ['Commute'],
    aiCategorized: true,
    clearSpendsConfidence: 0.97,
    createdAt: '2026-08-27T08:10:00Z',
    updatedAt: '2026-08-27T08:10:00Z',
  },
  {
    id: 'tx-007',
    date: '2026-08-25',
    merchant: 'Herman Miller',
    amount: 895.00,
    currency: 'USD',
    amountInUSD: 895.00,
    category: 'Shopping & Retail',
    subcategory: 'Furniture',
    accountId: 'acc-apple-card',
    tags: ['Ergonomics', 'WorkFromHome'],
    projectId: 'proj-home-office',
    notes: 'Aeron Ergonomic Office Chair upgrade',
    aiCategorized: true,
    clearSpendsConfidence: 0.95,
    createdAt: '2026-08-25T11:00:00Z',
    updatedAt: '2026-08-25T11:00:00Z',
  },
  {
    id: 'tx-008',
    date: '2026-08-24',
    merchant: 'Ben & Jerry\'s Scoops',
    amount: 14.50,
    currency: 'USD',
    amountInUSD: 14.50,
    category: 'Dining & Food',
    subcategory: 'Dessert',
    accountId: 'acc-cash-wallet',
    tags: ['Weekend', 'Treat'],
    aiCategorized: true,
    clearSpendsConfidence: 0.93,
    createdAt: '2026-08-24T20:15:00Z',
    updatedAt: '2026-08-24T20:15:00Z',
  },
  {
    id: 'tx-009',
    date: '2026-08-22',
    merchant: 'Spotify USA',
    amount: 16.99,
    currency: 'USD',
    amountInUSD: 16.99,
    category: 'Subscriptions & SaaS',
    subcategory: 'Music',
    accountId: 'acc-apple-card',
    tags: ['Subscription'],
    isRecurring: true,
    recurringId: 'rec-spotify',
    aiCategorized: true,
    clearSpendsConfidence: 0.99,
    createdAt: '2026-08-22T06:00:00Z',
    updatedAt: '2026-08-22T06:00:00Z',
  },
  {
    id: 'tx-010',
    date: '2026-08-20',
    merchant: 'Uber Technologies',
    amount: 28.30,
    currency: 'USD',
    amountInUSD: 28.30,
    category: 'Transportation',
    subcategory: 'Rideshare / Taxi',
    accountId: 'acc-amex-gold',
    tags: ['Evening', 'City'],
    aiCategorized: true,
    clearSpendsConfidence: 0.99,
    createdAt: '2026-08-20T23:10:00Z',
    updatedAt: '2026-08-20T23:10:00Z',
  },
  {
    id: 'tx-011',
    date: '2026-08-18',
    merchant: 'Sonic Fiber Corp',
    amount: 70.00,
    currency: 'USD',
    amountInUSD: 70.00,
    category: 'Utilities & Bills',
    subcategory: 'Internet',
    accountId: 'acc-chase-checking',
    tags: ['Monthly', 'Utility'],
    isRecurring: true,
    recurringId: 'rec-internet',
    aiCategorized: true,
    clearSpendsConfidence: 0.99,
    createdAt: '2026-08-18T09:00:00Z',
    updatedAt: '2026-08-18T09:00:00Z',
  },
  {
    id: 'tx-012',
    date: '2026-08-15',
    merchant: 'Trader Joe\'s #142',
    amount: 82.35,
    currency: 'USD',
    amountInUSD: 82.35,
    category: 'Groceries',
    subcategory: 'Supermarkets',
    accountId: 'acc-chase-checking',
    tags: ['WeeklyGrocery'],
    aiCategorized: true,
    clearSpendsConfidence: 0.99,
    createdAt: '2026-08-15T15:30:00Z',
    updatedAt: '2026-08-15T15:30:00Z',
  },
  {
    id: 'tx-013',
    date: '2026-08-14',
    merchant: 'Netflix.com',
    amount: 22.99,
    currency: 'USD',
    amountInUSD: 22.99,
    category: 'Subscriptions & SaaS',
    subcategory: 'Streaming Video',
    accountId: 'acc-apple-card',
    tags: ['Subscription'],
    isRecurring: true,
    recurringId: 'rec-netflix',
    aiCategorized: true,
    clearSpendsConfidence: 0.99,
    createdAt: '2026-08-14T06:00:00Z',
    updatedAt: '2026-08-14T06:00:00Z',
  },
  {
    id: 'tx-014',
    date: '2026-08-12',
    merchant: 'Apple Store Regent St',
    amount: 149.00,
    currency: 'GBP',
    amountInUSD: 190.72,
    category: 'Shopping & Retail',
    subcategory: 'Electronics & Gadgets',
    accountId: 'acc-apple-card',
    tags: ['TravelPurchase', 'Gadget'],
    notes: 'MagSafe battery and USB-C high-speed traveling hub',
    aiCategorized: true,
    clearSpendsConfidence: 0.96,
    createdAt: '2026-08-12T16:00:00Z',
    updatedAt: '2026-08-12T16:00:00Z',
  },
  {
    id: 'tx-015',
    date: '2026-08-10',
    merchant: 'Shinjuku Prince Hotel',
    amount: 45000,
    currency: 'JPY',
    amountInUSD: 306.00,
    category: 'Travel & Vacation',
    subcategory: 'Hotels & Airbnb',
    accountId: 'acc-amex-gold',
    tags: ['Tokyo', 'Hotel'],
    projectId: 'proj-japan-trip',
    notes: 'Deposit for Shinjuku accommodation in Tokyo',
    aiCategorized: true,
    clearSpendsConfidence: 0.97,
    createdAt: '2026-08-10T10:00:00Z',
    updatedAt: '2026-08-10T10:00:00Z',
  },
  {
    id: 'tx-016',
    date: '2026-08-08',
    merchant: 'OpenAI Services',
    amount: 20.00,
    currency: 'USD',
    amountInUSD: 20.00,
    category: 'Subscriptions & SaaS',
    subcategory: 'Software Tools',
    accountId: 'acc-apple-card',
    tags: ['AI', 'Work'],
    isRecurring: true,
    recurringId: 'rec-chatgpt',
    aiCategorized: true,
    clearSpendsConfidence: 0.99,
    createdAt: '2026-08-08T07:00:00Z',
    updatedAt: '2026-08-08T07:00:00Z',
  },
  {
    id: 'tx-017',
    date: '2026-08-05',
    merchant: 'Equinox Holdings',
    amount: 195.00,
    currency: 'USD',
    amountInUSD: 195.00,
    category: 'Healthcare & Fitness',
    subcategory: 'Gym Membership',
    accountId: 'acc-amex-gold',
    tags: ['Health', 'Fitness'],
    isRecurring: true,
    recurringId: 'rec-gym',
    aiCategorized: true,
    clearSpendsConfidence: 0.99,
    createdAt: '2026-08-05T06:00:00Z',
    updatedAt: '2026-08-05T06:00:00Z',
  },
  {
    id: 'tx-018',
    date: '2026-08-03',
    merchant: 'Target Supercenter',
    amount: 67.80,
    currency: 'USD',
    amountInUSD: 67.80,
    category: 'Shopping & Retail',
    subcategory: 'Home Goods',
    accountId: 'acc-chase-checking',
    tags: ['HomeSupplies'],
    aiCategorized: true,
    clearSpendsConfidence: 0.98,
    createdAt: '2026-08-03T18:45:00Z',
    updatedAt: '2026-08-03T18:45:00Z',
  },
  {
    id: 'tx-019',
    date: '2026-08-01',
    merchant: 'Metropolitan Real Estate',
    amount: 1750.00,
    currency: 'USD',
    amountInUSD: 1750.00,
    category: 'Housing & Rent',
    subcategory: 'Rent / Mortgage',
    accountId: 'acc-chase-checking',
    tags: ['Fixed', 'Monthly'],
    isRecurring: true,
    recurringId: 'rec-rent',
    aiCategorized: true,
    clearSpendsConfidence: 0.99,
    createdAt: '2026-08-01T08:00:00Z',
    updatedAt: '2026-08-01T08:00:00Z',
  },
  // July 2026 (Historical for Month-over-Month and Trends)
  {
    id: 'tx-020',
    date: '2026-07-28',
    merchant: 'Costco Wholesale',
    amount: 284.50,
    currency: 'USD',
    amountInUSD: 284.50,
    category: 'Groceries',
    subcategory: 'Supermarkets',
    accountId: 'acc-chase-checking',
    tags: ['Bulk', 'Grocery'],
    aiCategorized: true,
    clearSpendsConfidence: 0.99,
    createdAt: '2026-07-28T14:00:00Z',
    updatedAt: '2026-07-28T14:00:00Z',
  },
  {
    id: 'tx-021',
    date: '2026-07-20',
    merchant: 'Dell Technologies',
    amount: 420.00,
    currency: 'USD',
    amountInUSD: 420.00,
    category: 'Shopping & Retail',
    subcategory: 'Electronics & Gadgets',
    accountId: 'acc-apple-card',
    tags: ['Electronics', 'Monitor'],
    projectId: 'proj-home-office',
    notes: '27-inch 4K UltraSharp USB-C Monitor',
    aiCategorized: true,
    clearSpendsConfidence: 0.96,
    createdAt: '2026-07-20T10:00:00Z',
    updatedAt: '2026-07-20T10:00:00Z',
  },
  {
    id: 'tx-022',
    date: '2026-07-15',
    merchant: 'Nobu Japanese Dining',
    amount: 185.00,
    currency: 'USD',
    amountInUSD: 185.00,
    category: 'Dining & Food',
    subcategory: 'Restaurants',
    accountId: 'acc-amex-gold',
    tags: ['Dinner', 'FineDining'],
    aiCategorized: true,
    clearSpendsConfidence: 0.99,
    createdAt: '2026-07-15T21:00:00Z',
    updatedAt: '2026-07-15T21:00:00Z',
  },
  {
    id: 'tx-023',
    date: '2026-07-01',
    merchant: 'Metropolitan Real Estate',
    amount: 1750.00,
    currency: 'USD',
    amountInUSD: 1750.00,
    category: 'Housing & Rent',
    subcategory: 'Rent / Mortgage',
    accountId: 'acc-chase-checking',
    tags: ['Fixed', 'Monthly'],
    isRecurring: true,
    recurringId: 'rec-rent',
    aiCategorized: true,
    clearSpendsConfidence: 0.99,
    createdAt: '2026-07-01T08:00:00Z',
    updatedAt: '2026-07-01T08:00:00Z',
  },
  // Previous Year (2025) for Year-Over-Year Comparison
  {
    id: 'tx-024',
    date: '2025-08-15',
    merchant: 'Metropolitan Real Estate',
    amount: 1650.00,
    currency: 'USD',
    amountInUSD: 1650.00,
    category: 'Housing & Rent',
    subcategory: 'Rent / Mortgage',
    accountId: 'acc-chase-checking',
    tags: ['Historical2025'],
    aiCategorized: true,
    clearSpendsConfidence: 0.99,
    createdAt: '2025-08-15T08:00:00Z',
    updatedAt: '2025-08-15T08:00:00Z',
  },
  {
    id: 'tx-025',
    date: '2025-08-20',
    merchant: 'Whole Foods Market',
    amount: 410.00,
    currency: 'USD',
    amountInUSD: 410.00,
    category: 'Groceries',
    subcategory: 'Supermarkets',
    accountId: 'acc-amex-gold',
    tags: ['Historical2025'],
    aiCategorized: true,
    clearSpendsConfidence: 0.99,
    createdAt: '2025-08-20T12:00:00Z',
    updatedAt: '2025-08-20T12:00:00Z',
  },
  {
    id: 'tx-026',
    date: '2025-08-25',
    merchant: 'Dining & Restaurants Aggregate',
    amount: 520.00,
    currency: 'USD',
    amountInUSD: 520.00,
    category: 'Dining & Food',
    subcategory: 'Restaurants',
    accountId: 'acc-amex-gold',
    tags: ['Historical2025'],
    aiCategorized: true,
    clearSpendsConfidence: 0.99,
    createdAt: '2025-08-25T18:00:00Z',
    updatedAt: '2025-08-25T18:00:00Z',
  },
];
